name: If Conditinal

on:
  issues:
  pull_request:

jobs:
  test:
    if: ${{ contains(fromJSON('[vars.ISSUES_LABEL_LIST'), github.event.issue.labels.*.name) || contains(fromJSON('[vars.PR_LABEL_LIST'), github.event.pull_request.labels.*.name) }}
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo "${{ vars.ISSUES_LABEL_LIST }}"
        echo "${{ vars.PR_LABEL_LIST }}"
